package tech.csm.securelms.enums;

public enum SecurityEventType {
    USER_REGISTERED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    ACCOUNT_LOCKED_TEMPORARY,
    ACCOUNT_LOCKED_ADMIN_REQUIRED,
    ACCOUNT_UNLOCKED_ADMIN,
    ACCOUNT_LOCKED_BY_ADMIN,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    USER_LOCK_TOGGLED_BY_ADMIN,
    USER_ACTIVE_TOGGLED_BY_ADMIN
}
